import type { Metadata } from "next";
<<<<<<< HEAD
import { Playfair_Display, DM_Sans } from "next/font/google";
=======
>>>>>>> 01bcb1f (Sync codebase)
import "./globals.css";
import VisualEditsMessenger from "../visual-edits/VisualEditsMessenger";
import ErrorReporter from "@/components/ErrorReporter";
import Script from "next/script";
<<<<<<< HEAD
import { Sidebar } from "@/components/Sidebar";
import { Toaster } from "@/components/ui/sonner";

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
});

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Sonakshi Boutique POS",
  description: "Point of Sale System for Sonakshi Boutique",
=======

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> 01bcb1f (Sync codebase)
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body className={`${playfair.variable} ${dmSans.variable} font-sans antialiased bg-slate-950`}>
        <Script
          id="orchids-browser-logs"
          src="https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/scripts/orchids-browser-logs.js"
          strategy="afterInteractive"
          data-orchids-project-id="6e37d457-ea93-4b80-875c-9e3fc0eee51a"
        />
=======
      <body className="antialiased">
>>>>>>> 01bcb1f (Sync codebase)
        <ErrorReporter />
        <Script
          src="https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/scripts//route-messenger.js"
          strategy="afterInteractive"
          data-target-origin="*"
          data-message-type="ROUTE_CHANGE"
          data-include-search-params="true"
          data-only-in-iframe="true"
          data-debug="true"
          data-custom-data='{"appName": "YourApp", "version": "1.0.0", "greeting": "hi"}'
        />
<<<<<<< HEAD
        <Sidebar />
        <main className="ml-64 min-h-screen">
          {children}
        </main>
        <Toaster position="top-right" richColors />
=======
        {children}
>>>>>>> 01bcb1f (Sync codebase)
        <VisualEditsMessenger />
      </body>
    </html>
  );
}
